"""empty message

Revision ID: 780a67bb86ec
Revises: 
Create Date: 2020-10-02 19:59:30.753425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780a67bb86ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_header', sa.String(), nullable=True),
    sa.Column('raw_data', sa.String(), nullable=True),
    sa.Column('raw_form', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    # ### end Alembic commands ###
